package output

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/nitrogate/nitrogate/internal/attest"
	"github.com/nitrogate/nitrogate/internal/gate"
	"github.com/nitrogate/nitrogate/internal/scanner"
)

func BuildPRComment(gateResult gate.GateResult, attestResult string, signed *attest.SignedAttestation) string {
	var b strings.Builder

	b.WriteString("## NitroGate Quality Gate\n\n")
	b.WriteString(gateResult.FormatSummaryLine())
	b.WriteString("\n\n")

	for _, r := range gateResult.ScanResults {
		icon := "✅"
		if r.HasBlocking(scanner.SeverityHigh) {
			icon = "❌"
		} else if r.HasBlocking(scanner.SeverityMedium) {
			icon = "⚠️"
		}

		if len(r.Findings) == 0 && r.Error == "" {
			b.WriteString(fmt.Sprintf("%s **%s** — No issues found (%s)\n\n", icon, formatScannerName(r.Scanner), r.Duration))
			continue
		}

		findingCount := len(r.Findings)
		b.WriteString(fmt.Sprintf("%s **%s** — %d finding(s) (%s)\n\n", icon, formatScannerName(r.Scanner), findingCount, r.Duration))

		if r.Error != "" {
			b.WriteString(fmt.Sprintf("> ⚠️ Scanner error: %s\n\n", r.Error))
		}

		shown := 0
		for _, f := range r.Findings {
			if f.Severity < scanner.SeverityMedium {
				continue
			}
			if shown >= 5 {
				remaining := countAboveThreshold(r.Findings[shown:], scanner.SeverityMedium)
				if remaining > 0 {
					b.WriteString(fmt.Sprintf("  ... and %d more\n", remaining))
				}
				break
			}
			sevIcon := severityIcon(f.Severity)
			b.WriteString(fmt.Sprintf("  %s **%s**: %s\n", sevIcon, f.Title, f.Detail))
			if f.File != "" {
				b.WriteString(fmt.Sprintf("    📄 `%s`", f.File))
				if f.Line > 0 {
					b.WriteString(fmt.Sprintf(":%d", f.Line))
				}
				b.WriteString("\n")
			}
			if f.Remediation != "" {
				b.WriteString(fmt.Sprintf("    💡 %s\n", truncateRem(f.Remediation)))
			}
			b.WriteString("\n")
			shown++
		}
	}

	b.WriteString("---\n\n")
	b.WriteString(buildAttestationSection(attestResult, signed))
	b.WriteString(fmt.Sprintf("**Mode**: %s\n\n", gateResult.Mode))

	b.WriteString("<details>\n<summary>Summary</summary>\n\n")
	b.WriteString(fmt.Sprintf("| Severity | Count |\n|---|---|\n"))
	b.WriteString(fmt.Sprintf("| 🔴 Critical | %d |\n", gateResult.Summary.CriticalCount))
	b.WriteString(fmt.Sprintf("| 🟠 High | %d |\n", gateResult.Summary.HighCount))
	b.WriteString(fmt.Sprintf("| 🟡 Medium | %d |\n", gateResult.Summary.MediumCount))
	b.WriteString(fmt.Sprintf("| 🔵 Low | %d |\n", gateResult.Summary.LowCount))
	b.WriteString(fmt.Sprintf("| ℹ️ Info | %d |\n", gateResult.Summary.InfoCount))
	b.WriteString(fmt.Sprintf("\nScanners run: %d\n", gateResult.Summary.ScannersRun))
	b.WriteString("\n</details>\n\n")

	b.WriteString("<!-- nitrogate-review -->\n")
	b.WriteString("*Generated by [NitroGate](https://github.com/nitrogate/nitrogate) — Supply Chain Quality Gate*\n")

	return b.String()
}

func WriteArtifacts(outputDir string, gateResult gate.GateResult, signed *attest.SignedAttestation) error {
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return err
	}

	gateJSON, _ := json.MarshalIndent(gateResult, "", "  ")
	if err := os.WriteFile(filepath.Join(outputDir, "gate-result.json"), gateJSON, 0644); err != nil {
		return err
	}

	if signed != nil {
		attestJSON, _ := json.MarshalIndent(signed, "", "  ")
		if err := os.WriteFile(filepath.Join(outputDir, "attestation.json"), attestJSON, 0644); err != nil {
			return err
		}
	}

	findingsJSON, _ := json.MarshalIndent(collectAllFindings(gateResult), "", "  ")
	if err := os.WriteFile(filepath.Join(outputDir, "findings.json"), findingsJSON, 0644); err != nil {
		return err
	}

	return nil
}

func buildAttestationSection(attestResult string, signed *attest.SignedAttestation) string {
	var b strings.Builder

	if signed == nil || attestResult != "SIGNED" {
		b.WriteString(fmt.Sprintf("**Attestation**: ⏭️ %s\n\n", attestResult))
		if attestResult == "SKIPPED" {
			b.WriteString("> _No signing key configured. Add `NITRO_SIGNING_KEY_B64` secret to enable tamper-proof attestations._\n\n")
		}
		return b.String()
	}

	stmt, err := attest.ExtractStatement(signed)
	if err != nil {
		b.WriteString("**Attestation**: ⚠️ SIGNED (could not extract details)\n\n")
		return b.String()
	}

	b.WriteString("### 🔏 Attestation: SIGNED & VERIFIED\n\n")
	b.WriteString("This scan result is cryptographically signed. The attestation proves these results are authentic and have not been tampered with.\n\n")

	b.WriteString("<details>\n<summary>📜 Attestation Details</summary>\n\n")

	b.WriteString("| Property | Value |\n|---|---|\n")
	b.WriteString(fmt.Sprintf("| **Format** | [in-toto v1](https://github.com/in-toto/attestation/tree/main/spec/v1) (DSSE envelope) |\n"))
	b.WriteString(fmt.Sprintf("| **Predicate** | `%s` |\n", stmt.PredicateType))
	b.WriteString(fmt.Sprintf("| **Algorithm** | Ed25519 |\n"))

	pubKeyShort := signed.PublicKey
	if len(pubKeyShort) > 16 {
		pubKeyShort = pubKeyShort[:8] + "..." + pubKeyShort[len(pubKeyShort)-8:]
	}
	b.WriteString(fmt.Sprintf("| **Public Key** | `%s` |\n", pubKeyShort))
	b.WriteString(fmt.Sprintf("| **Signed At** | %s |\n", signed.Timestamp))

	sigShort := signed.Envelope.Signatures[0].Sig
	if len(sigShort) > 24 {
		sigShort = sigShort[:12] + "..." + sigShort[len(sigShort)-12:]
	}
	b.WriteString(fmt.Sprintf("| **Signature** | `%s` |\n", sigShort))

	if len(stmt.Subject) > 0 {
		subj := stmt.Subject[0]
		b.WriteString(fmt.Sprintf("| **Subject** | `%s` |\n", subj.Name))
		if digest, ok := subj.Digest["sha256"]; ok {
			short := digest
			if len(short) > 16 {
				short = short[:16] + "..."
			}
			b.WriteString(fmt.Sprintf("| **Commit Digest** | `sha256:%s` |\n", short))
		}
	}

	payloadHash := sha256Hex([]byte(signed.Envelope.Payload))
	b.WriteString(fmt.Sprintf("| **Payload Hash** | `sha256:%s...` |\n", payloadHash[:16]))

	b.WriteString(fmt.Sprintf("\n**Gate Decision at signing**: %s\n", stmt.Predicate.Gate.Decision))
	b.WriteString(fmt.Sprintf("**Findings at signing**: %d total\n", stmt.Predicate.Gate.Summary.TotalFindings))

	b.WriteString("\n</details>\n\n")

	return b.String()
}

func sha256Hex(data []byte) string {
	h := sha256.Sum256(data)
	return hex.EncodeToString(h[:])
}

type InlineComment struct {
	Path string
	Line int
	Body string
}

func BuildInlineComments(gateResult gate.GateResult) []InlineComment {
	var comments []InlineComment
	for _, r := range gateResult.ScanResults {
		for _, f := range r.Findings {
			if f.File == "" || f.Line <= 0 {
				continue
			}
			if f.Severity < scanner.SeverityMedium {
				continue
			}
			var b strings.Builder
			b.WriteString(fmt.Sprintf("%s **%s**\n\n", severityIcon(f.Severity), f.Title))
			b.WriteString(f.Detail + "\n\n")
			if f.Remediation != "" {
				b.WriteString(fmt.Sprintf("💡 %s\n\n", f.Remediation))
			}
			b.WriteString(fmt.Sprintf("_— NitroGate %s_", formatScannerName(r.Scanner)))
			comments = append(comments, InlineComment{
				Path: f.File,
				Line: f.Line,
				Body: b.String(),
			})
		}
	}
	return comments
}

func collectAllFindings(g gate.GateResult) []scanner.Finding {
	var all []scanner.Finding
	for _, r := range g.ScanResults {
		all = append(all, r.Findings...)
	}
	return all
}

func formatScannerName(name string) string {
	names := map[string]string{
		"secrets":      "Secrets",
		"dependencies": "Dependencies",
		"licenses":     "Licenses",
		"workflows":    "Workflow Security",
		"npm-supply":   "NPM Supply Chain",
		"llm-review":   "AI Code Review",
	}
	if n, ok := names[name]; ok {
		return n
	}
	return strings.Title(name)
}

func severityIcon(s scanner.Severity) string {
	switch s {
	case scanner.SeverityCritical:
		return "🔴"
	case scanner.SeverityHigh:
		return "🟠"
	case scanner.SeverityMedium:
		return "🟡"
	case scanner.SeverityLow:
		return "🔵"
	default:
		return "ℹ️"
	}
}

func countAboveThreshold(findings []scanner.Finding, threshold scanner.Severity) int {
	count := 0
	for _, f := range findings {
		if f.Severity >= threshold {
			count++
		}
	}
	return count
}

func truncateRem(s string) string {
	lines := strings.Split(s, "\n")
	if len(lines) > 1 {
		return lines[0]
	}
	if len(s) > 120 {
		return s[:117] + "..."
	}
	return s
}
