import * as fs from 'fs';
import * as path from 'path';
import { LLMReview } from './schema';
import { Attestation, Evidence } from './attest/types';
import { PolicyViolation } from './policy';

export interface ArtifactPaths {
  review: string;
  evidence: string;
  attestation: string;
}

export function writeArtifacts(
  outputDir: string,
  review: LLMReview,
  evidence: Evidence,
  attestation: Attestation | null,
): ArtifactPaths {
  fs.mkdirSync(outputDir, { recursive: true });

  const reviewPath = path.join(outputDir, 'review.json');
  const evidencePath = path.join(outputDir, 'evidence.json');
  const attestationPath = path.join(outputDir, 'attestation.json');

  fs.writeFileSync(reviewPath, JSON.stringify(review, null, 2));
  fs.writeFileSync(evidencePath, JSON.stringify(evidence, null, 2));
  if (attestation) {
    fs.writeFileSync(attestationPath, JSON.stringify(attestation, null, 2));
  }

  return { review: reviewPath, evidence: evidencePath, attestation: attestationPath };
}

export function buildPRComment(
  review: LLMReview,
  violations: PolicyViolation[],
  attestationResult: 'PASS' | 'FAIL' | 'SKIPPED',
  llmValid: boolean,
  mode: string,
): string {
  const lines: string[] = [];
  lines.push('## AflockGate PR Review');
  lines.push('');

  if (violations.length > 0) {
    lines.push(`### Policy Violations (${violations.length})`);
    for (const v of violations) {
      lines.push(`- **${v.type}**: ${v.message}`);
    }
    lines.push('');
  }

  lines.push(`### Summary`);
  lines.push(review.summary);
  lines.push('');

  if (!llmValid) {
    lines.push('> **Note:** LLM output was invalid; showing fallback review.');
    lines.push('');
  }

  if (review.blocking.length > 0) {
    lines.push(`### Blocking Issues (${review.blocking.length})`);
    const shown = review.blocking.slice(0, 3);
    for (const issue of shown) {
      lines.push(`- **${issue.title}**: ${issue.detail}`);
      if (issue.files.length > 0) {
        lines.push(`  Files: \`${issue.files.join('`, `')}\``);
      }
    }
    if (review.blocking.length > 3) {
      lines.push(`- ... and ${review.blocking.length - 3} more`);
    }
    lines.push('');
  }

  if (review.nonBlocking.length > 0) {
    lines.push(`### Non-Blocking Suggestions (${review.nonBlocking.length})`);
    const shown = review.nonBlocking.slice(0, 3);
    for (const issue of shown) {
      lines.push(`- **${issue.title}**: ${issue.detail}`);
    }
    if (review.nonBlocking.length > 3) {
      lines.push(`- ... and ${review.nonBlocking.length - 3} more`);
    }
    lines.push('');
  }

  if (review.testPlan.length > 0) {
    lines.push('### Test Plan');
    for (const item of review.testPlan) {
      lines.push(`- [${item.type}] ${item.what}`);
    }
    lines.push('');
  }

  lines.push(`### Attestation: ${attestationResult}`);
  lines.push(`Mode: **${mode}**`);
  lines.push('');
  lines.push('---');
  lines.push('*Generated by AflockGate under policy `.aflock.json`; do not paste secrets.*');

  return lines.join('\n');
}
